"""initial schema

Revision ID: 63fb60267759
Revises: 
Create Date: 2026-07-31 17:11:19.790168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63fb60267759'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('institution', sa.String(length=20), nullable=False),
    sa.Column('term_code', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=10), nullable=False),
    sa.Column('sections_found', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(length=20), nullable=False),
    sa.Column('discord_username', sa.String(length=32), nullable=False),
    sa.Column('discord_avatar', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_table('section_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('class_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['scrape_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshots_class', 'section_snapshots', ['class_number', 'scraped_at'], unique=False)
    op.create_table('sections',
    sa.Column('class_number', sa.Integer(), nullable=False),
    sa.Column('term_code', sa.String(length=10), nullable=False),
    sa.Column('institution', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=10), nullable=False),
    sa.Column('course_number', sa.String(length=10), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.Column('section_code', sa.String(length=30), nullable=False),
    sa.Column('days_times', sa.String(length=100), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=False),
    sa.Column('instructor', sa.String(length=100), nullable=False),
    sa.Column('instruction_mode', sa.String(length=60), nullable=False),
    sa.Column('meeting_dates', sa.String(length=60), nullable=False),
    sa.Column('course_topic', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_seen_run', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_seen_run'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('class_number')
    )
    op.create_table('watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_number', sa.Integer(), nullable=False),
    sa.Column('notify_on', sa.String(length=20), nullable=False),
    sa.Column('auto_deactivate', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'class_number')
    )
    op.create_index('idx_watches_class', 'watches', ['class_number'], unique=False, postgresql_where='active = TRUE')
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('watch_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=False),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['scrape_runs.id'], ),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watch_id', 'from_status', 'to_status', name='uq_notifications_dedup')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_index('idx_watches_class', table_name='watches', postgresql_where='active = TRUE')
    op.drop_table('watches')
    op.drop_table('sections')
    op.drop_index('idx_snapshots_class', table_name='section_snapshots')
    op.drop_table('section_snapshots')
    op.drop_table('students')
    op.drop_table('scrape_runs')
    # ### end Alembic commands ###
