"""add fetch_key to sections

Revision ID: c66ed2859d24
Revises: c9164e87a18e
Create Date: 2026-07-31 20:02:58.823948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66ed2859d24'
down_revision: Union[str, Sequence[str], None] = 'c9164e87a18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('fetch_key', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'fetch_key')
    # ### end Alembic commands ###
